<a href="https://colab.research.google.com/github/ArunK-ML/Chennai_Train_Sales-Data-Preprocessing-Analyze/blob/main/Train_Sales_Data.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("/content/train-chennai-sale.csv")
df

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,...,AllPub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,...,AllPub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,...,AllPub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,...,NoSeWa,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,...,NoSeWa,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [3]:
df.columns

# lot of spelling mistakes in colums name

Index(['PRT_ID', 'AREA', 'INT_SQFT', 'DATE_SALE', 'DIST_MAINROAD', 'N_BEDROOM',
       'N_BATHROOM', 'N_ROOM', 'SALE_COND', 'PARK_FACIL', 'DATE_BUILD',
       'BUILDTYPE', 'UTILITY_AVAIL', 'STREET', 'MZZONE', 'QS_ROOMS',
       'QS_BATHROOM', 'QS_BEDROOM', 'QS_OVERALL', 'REG_FEE', 'COMMIS',
       'SALES_PRICE'],
      dtype='object')

In [6]:
df['AREA']= df['AREA'].replace({"Ana Nagar":"Anna Nagar",
                                "Ann Nagar":"Anna Nagar",
                                "Karapakam":"Karapakkam",
                                "Adyr":"Adyar",
                                "TNagar":"T Nagar",
                                "Velchery":"Velachery",
                                "Chrompt":"Chrompet",
                                "Chormpet":"Chrompet",
                                "Chrmpet":"Chrompet",
                                "KKNagar":"KK Nagar"})

In [10]:
df['AREA'].unique()

array(['Karapakkam', 'Anna Nagar', 'Adyar', 'Velachery', 'Chrompet',
       'KK Nagar', 'T Nagar'], dtype=object)

In [7]:
df['SALE_COND'].unique()

array(['AbNormal', 'Family', 'Partial', 'AdjLand', 'Normal Sale',
       'Ab Normal', 'Partiall', 'Adj Land', 'PartiaLl'], dtype=object)

In [8]:
df['SALE_COND']= df['SALE_COND'].replace({"Ab Normal":"AbNormal",
                                          "Partiall":"Partial",
                                          "PartiaLl":"Partial",
                                          "Adj Land":"AdjLand"})

In [11]:
df['SALE_COND'].unique()

array(['AbNormal', 'Family', 'Partial', 'AdjLand', 'Normal Sale'],
      dtype=object)

In [12]:
df['PARK_FACIL'].unique()

array(['Yes', 'No', 'Noo'], dtype=object)

In [13]:
df["PARK_FACIL"] = df["PARK_FACIL"].apply(lambda i:"No" if i=="Noo" else i)

In [14]:
df['PARK_FACIL'].unique()

array(['Yes', 'No'], dtype=object)

In [15]:
df["BUILDTYPE"].unique()

array(['Commercial', 'Others', 'Other', 'House', 'Comercial'],
      dtype=object)

In [16]:
df['BUILDTYPE']= df['BUILDTYPE'].replace({"Other":"Others",
                                          "Comercial":"Commercial"})

In [17]:
df["BUILDTYPE"].unique()

array(['Commercial', 'Others', 'House'], dtype=object)

In [18]:
df["UTILITY_AVAIL"].unique()

array(['AllPub', 'ELO', 'NoSewr ', 'NoSeWa', 'All Pub'], dtype=object)

In [19]:
df['UTILITY_AVAIL']= df['UTILITY_AVAIL'].replace({"AllPub":"All Pub",
                                          "NoSeWa":"NoSewr "})

In [20]:
df["UTILITY_AVAIL"].unique()

array(['All Pub', 'ELO', 'NoSewr '], dtype=object)

In [21]:
df["STREET"].unique()

array(['Paved', 'Gravel', 'No Access', 'Pavd', 'NoAccess'], dtype=object)

In [22]:
df['STREET']= df['STREET'].replace({"Pavd":"Paved",
                                          "NoAccess":"No Access"})

In [23]:
df["STREET"].unique()

array(['Paved', 'Gravel', 'No Access'], dtype=object)

In [24]:
df["MZZONE"].unique()

array(['A', 'RH', 'RL', 'I', 'C', 'RM'], dtype=object)

In [25]:
df1 = df.copy()

In [26]:
df1

,PRT_ID,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
0,P03210,Karapakkam,1004,04-05-2011,131,1.0,1.0,3,AbNormal,Yes,...,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
1,P09411,Anna Nagar,1986,19-12-2006,26,2.0,1.0,5,AbNormal,No,...,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
2,P01812,Adyar,909,04-02-2012,70,1.0,1.0,3,AbNormal,Yes,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
3,P05346,Velachery,1855,13-03-2010,14,3.0,2.0,5,Family,No,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
4,P06210,Karapakkam,1226,05-10-2009,84,1.0,1.0,3,AbNormal,Yes,...,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7104,P03834,Karapakkam,598,03-01-2011,51,1.0,1.0,2,AdjLand,No,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
7105,P10000,Velachery,1897,08-04-2004,52,3.0,2.0,5,Family,Yes,...,NoSewr,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
7106,P09594,Velachery,1614,25-08-2006,152,2.0,1.0,4,Normal Sale,No,...,NoSewr,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
7107,P06508,Karapakkam,787,03-08-2009,40,1.0,1.0,2,Partial,Yes,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
7108,P09794,Velachery,1896,13-07-2005,156,3.0,2.0,5,Partial,Yes,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [27]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

PRT_ID ['P03210' 'P09411' 'P01812' ... 'P09594' 'P06508' 'P09794']
AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
DATE_SALE ['04-05-2011' '19-12-2006' '04-02-2012' ... '28-03-2014' '25-08-2006'
 '13-07-2005']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
PARK_FACIL ['Yes' 'No']
DATE_BUILD ['15-05-1967' '22-12-1995' '09-02-1992' ... '01-09-1978' '11-08-1977'
 '24-07-1961']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['All Pub' 'ELO' 'NoSewr ']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [28]:
# Date data type correcting

df["DATE_SALE"]=pd.to_datetime(df["DATE_SALE"],format="%d-%m-%Y")

In [29]:
df["DATE_BUILD"]=pd.to_datetime(df["DATE_BUILD"],format="%d-%m-%Y")

In [30]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

PRT_ID ['P03210' 'P09411' 'P01812' ... 'P09594' 'P06508' 'P09794']
AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
PARK_FACIL ['Yes' 'No']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['All Pub' 'ELO' 'NoSewr ']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [31]:
df["PRT_ID"].nunique()

7109

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7109 entries, 0 to 7108
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   PRT_ID         7109 non-null   object
 1   AREA           7109 non-null   object
 2   INT_SQFT       7109 non-null   int64
 3   DATE_SALE      7109 non-null   datetime64[ns]
 4   DIST_MAINROAD  7109 non-null   int64
 5   N_BEDROOM      7108 non-null   float64
 6   N_BATHROOM     7104 non-null   float64
 7   N_ROOM         7109 non-null   int64
 8   SALE_COND      7109 non-null   object
 9   PARK_FACIL     7109 non-null   object
 10  DATE_BUILD     7109 non-null   datetime64[ns]
 11  BUILDTYPE      7109 non-null   object
 12  UTILITY_AVAIL  7109 non-null   object
 13  STREET         7109 non-null   object
 14  MZZONE         7109 non-null   object
 15  QS_ROOMS       7109 non-null   float64
 16  QS_BATHROOM    7109 non-null   float64
 17  QS_BEDROOM     7109 non-null   float64
 18  QS_OVERALL     7061 non-null   float64
 19  REG_FEE        7109 non-null   int64
 20  COMMIS         7109 non-null   int64
 21  SALES_PRICE    7109 non-null   int64
dtypes: datetime64[ns](2), float64(6), int64(6), object(8)
memory usage: 1.2+ MB

In [33]:
df.set_index("PRT_ID", inplace = True) # making prt_id to the index

In [34]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,Yes,1967-05-15,...,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,No,1995-12-22,...,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,Yes,1992-02-09,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,No,1988-03-18,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,Yes,1979-10-13,...,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,No,1962-01-15,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,Yes,1995-04-11,...,NoSewr,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,No,1978-09-01,...,NoSewr,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,Yes,1977-08-11,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,Yes,1961-07-24,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480

In [35]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
PARK_FACIL ['Yes' 'No']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['All Pub' 'ELO' 'NoSewr ']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [36]:
df["PARK_FACIL"]=df["PARK_FACIL"].replace({"Yes":1,
                                           "No":0})

/tmp/ipython-input-36-3382051475.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["PARK_FACIL"]=df["PARK_FACIL"].replace({"Yes":1,

In [37]:
for i in df.select_dtypes(include=["object"]).columns:
  print(i,df[i].unique())

AREA ['Karapakkam' 'Anna Nagar' 'Adyar' 'Velachery' 'Chrompet' 'KK Nagar'
 'T Nagar']
SALE_COND ['AbNormal' 'Family' 'Partial' 'AdjLand' 'Normal Sale']
BUILDTYPE ['Commercial' 'Others' 'House']
UTILITY_AVAIL ['All Pub' 'ELO' 'NoSewr ']
STREET ['Paved' 'Gravel' 'No Access']
MZZONE ['A' 'RH' 'RL' 'I' 'C' 'RM']

In [38]:
df

,AREA,INT_SQFT,DATE_SALE,DIST_MAINROAD,N_BEDROOM,N_BATHROOM,N_ROOM,SALE_COND,PARK_FACIL,DATE_BUILD,...,UTILITY_AVAIL,STREET,MZZONE,QS_ROOMS,QS_BATHROOM,QS_BEDROOM,QS_OVERALL,REG_FEE,COMMIS,SALES_PRICE
PRT_ID,,,,,,,,,,,,,,,,,,,,,
P03210,Karapakkam,1004,2011-05-04,131,1.0,1.0,3,AbNormal,1,1967-05-15,...,All Pub,Paved,A,4.0,3.9,4.9,4.330,380000,144400,7600000
P09411,Anna Nagar,1986,2006-12-19,26,2.0,1.0,5,AbNormal,0,1995-12-22,...,All Pub,Gravel,RH,4.9,4.2,2.5,3.765,760122,304049,21717770
P01812,Adyar,909,2012-02-04,70,1.0,1.0,3,AbNormal,1,1992-02-09,...,ELO,Gravel,RL,4.1,3.8,2.2,3.090,421094,92114,13159200
P05346,Velachery,1855,2010-03-13,14,3.0,2.0,5,Family,0,1988-03-18,...,NoSewr,Paved,I,4.7,3.9,3.6,4.010,356321,77042,9630290
P06210,Karapakkam,1226,2009-10-05,84,1.0,1.0,3,AbNormal,1,1979-10-13,...,All Pub,Gravel,C,3.0,2.5,4.1,3.290,237000,74063,7406250
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
P03834,Karapakkam,598,2011-01-03,51,1.0,1.0,2,AdjLand,0,1962-01-15,...,ELO,No Access,RM,3.0,2.2,2.4,2.520,208767,107060,5353000
P10000,Velachery,1897,2004-04-08,52,3.0,2.0,5,Family,1,1995-04-11,...,NoSewr,No Access,RH,3.6,4.5,3.3,3.920,346191,205551,10818480
P09594,Velachery,1614,2006-08-25,152,2.0,1.0,4,Normal Sale,0,1978-09-01,...,NoSewr,Gravel,I,4.3,4.2,2.9,3.840,317354,167028,8351410
P06508,Karapakkam,787,2009-08-03,40,1.0,1.0,2,Partial,1,1977-08-11,...,ELO,Paved,RL,4.6,3.8,4.1,4.160,425350,119098,8507000
P09794,Velachery,1896,2005-07-13,156,3.0,2.0,5,Partial,1,1961-07-24,...,ELO,Paved,I,3.1,3.5,4.3,3.640,349177,79812,9976480